/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -i agent_adaptor.h -l LocationServices -i location/locationservices.h -a :agent_adaptor.cpp ../../theShell/shell/org.freedesktop.GeoClue2.Agent.xml
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "agent_adaptor.h"
#include "location/locationservices.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class AgentAdaptor
 */

AgentAdaptor::AgentAdaptor(LocationServices *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

AgentAdaptor::~AgentAdaptor()
{
    // destructor
}

uint AgentAdaptor::maxAccuracyLevel() const
{
    // get the value of property MaxAccuracyLevel
    return qvariant_cast< uint >(parent()->property("MaxAccuracyLevel"));
}

void AgentAdaptor::AuthorizeApp(const QString &desktop_id, uint req_accuracy_level, bool &authorized, uint &allowed_accuracy_level)
{
    // handle method call org.freedesktop.GeoClue2.Agent.AuthorizeApp
    authorized = parent()->AuthorizeApp(desktop_id, req_accuracy_level, allowed_accuracy_level);
}

