/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a jobviewserver_adaptor.h: ../../../theShell/daemons/ts-kuiserver/org.kde.JobViewServer.xml
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef JOBVIEWSERVER_ADAPTOR_H
#define JOBVIEWSERVER_ADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.kde.JobViewServer
 */
class JobViewServerAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.kde.JobViewServer")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.kde.JobViewServer\">\n"
"    <method name=\"requestView\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"appName\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"appIconName\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"capabilities\"/>\n"
"      <arg direction=\"out\" type=\"o\" name=\"trackerPath\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    JobViewServerAdaptor(QObject *parent);
    virtual ~JobViewServerAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    QDBusObjectPath requestView(const QString &appName, const QString &appIconName, int capabilities);
Q_SIGNALS: // SIGNALS
};

class KuiServerAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.kde.kuiserver")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.kde.kuiserver\">\n"
"    <signal name=\"jobUrlsChanged\">\n"
"      <arg direction=\"out\" type=\"as\" name=\"jobUrls\"/>\n"
"    </signal>\n"
"    <method name=\"registerService\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"service\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"objectPath\"/>\n"
"    </method>\n"
"    <method name=\"emitJobUrlsChanged\"/>\n"
"    <method name=\"requiresJobTracker\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"    </method>\n"
"    <method name=\"registeredJobContacts\">\n"
"      <arg direction=\"out\" type=\"as\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    KuiServerAdaptor(QObject *parent);
    virtual ~KuiServerAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void emitJobUrlsChanged();
    void registerService(const QString &service, const QString &objectPath);
    QStringList registeredJobContacts();
    bool requiresJobTracker();
Q_SIGNALS: // SIGNALS
    void jobUrlsChanged(QStringList jobUrls);
};

#endif
