/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -i jobviewserver_adaptor.h -a :jobviewserver_adaptor.cpp ../../../theShell/daemons/ts-kuiserver/org.kde.JobViewServer.xml
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "jobviewserver_adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

#include "jobserver.h"

/*
 * Implementation of adaptor class JobViewServerAdaptor
 */

JobViewServerAdaptor::JobViewServerAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

JobViewServerAdaptor::~JobViewServerAdaptor()
{
    // destructor
}

KuiServerAdaptor::KuiServerAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    //setAutoRelaySignals(true);
}

KuiServerAdaptor::~KuiServerAdaptor()
{
    // destructor
}


QDBusObjectPath JobViewServerAdaptor::requestView(const QString &appName, const QString &appIconName, int capabilities)
{
    // handle method call org.kde.JobViewServer.requestView
    return qobject_cast<JobServer*>(parent())->requestView(appName, appIconName, capabilities);
}

void KuiServerAdaptor::emitJobUrlsChanged() {
    qDebug() << "job urls changed";
    emit jobUrlsChanged(QStringList());
}

void KuiServerAdaptor::registerService(const QString &service, const QString &objectPath) {
    qDebug() << "Registering service" << service << "at" << objectPath;
}

bool KuiServerAdaptor::requiresJobTracker() {
    qDebug() << "require job tracker";
    return false;
}

QStringList KuiServerAdaptor::registeredJobContacts() {
    qDebug() << "registered job contacts";
    return QStringList();
}
